#ifndef MESSYCODE2D_GLOBAL_H
#define MESSYCODE2D_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESSYCODE2D_LIBRARY)
#  define MESSYCODE2DSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESSYCODE2DSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSYCODE2D_GLOBAL_H
